// Set default filter attributes
export const SET_DEFAULT_FILTER_ATTS = 'SET_DEFAULT_FILTER_ATTS';

export const FETCH_PRODUCTS_REQUEST = 'FETCH_PRODUCTS_REQUEST';
export const FETCH_PRODUCTS_SUCCESS = 'FETCH_PRODUCTS_SUCCESS';
export const FETCH_PRODUCTS_FAILURE = 'FETCH_PRODUCTS_FAILURE';

// Set default filter attributes
export const FETCH_PROPS_REQUEST = 'FETCH_PROPS_REQUEST';
export const FETCH_PROPS_SUCCESS = 'FETCH_PROPS_SUCCESS';
export const FETCH_PROPS_FAILURE = 'FETCH_PROPS_FAILURE';

