// Set default filter attributes
export const SET_DEFAULT_FILTER_ATTS = 'SET_DEFAULT_FILTER_ATTS';
export const SET_CURRENT_FILTER_ATTS = 'SET_CURRENT_FILTER_ATTS';

export const FETCH_PRODUCTS_REQUEST = 'FETCH_PRODUCTS_REQUEST';
export const FETCH_PRODUCTS_SUCCESS = 'FETCH_PRODUCTS_SUCCESS';
export const FETCH_PRODUCTS_FAILURE = 'FETCH_PRODUCTS_FAILURE';
export const FETCH_PRODUCTS_CANCEL = 'FETCH_PRODUCTS_CANCEL';

export const SAVE_LDS_PROPERTIES = 'SAVE_LDS_PROPERTIES';

